import type { DebtItem, Repo, Sprint, TeamMember, WeeklyStats, ModuleDebt } from '@/types'

// ── REPOS ─────────────────────────────────────────────────────────────────────
export const MOCK_REPOS: Repo[] = [
  {
    id: 'repo-1',
    workspace_id: 'ws-1',
    name: 'api-server',
    provider: 'github',
    full_name: 'acme/api-server',
    url: 'https://github.com/acme/api-server',
    default_branch: 'main',
    health_score: 42,
    last_scanned: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'repo-2',
    workspace_id: 'ws-1',
    name: 'frontend-app',
    provider: 'github',
    full_name: 'acme/frontend-app',
    url: 'https://github.com/acme/frontend-app',
    default_branch: 'main',
    health_score: 67,
    last_scanned: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'repo-3',
    workspace_id: 'ws-1',
    name: 'mobile-app',
    provider: 'gitlab',
    full_name: 'acme/mobile-app',
    url: 'https://gitlab.com/acme/mobile-app',
    default_branch: 'main',
    health_score: 81,
    last_scanned: new Date(Date.now() - 86400000).toISOString(),
  },
]

// ── DEBT ITEMS ────────────────────────────────────────────────────────────────
export const MOCK_DEBT_ITEMS: DebtItem[] = [
  {
    id: 'debt-1',
    repo_id: 'repo-1',
    title: 'Token expiry race condition causes random logouts',
    description: 'When multiple browser tabs are open, simultaneous refresh requests cause a race condition. One request succeeds, the other gets a 401 and logs the user out unexpectedly.',
    file_path: 'src/auth/token.service.ts',
    line_start: 47,
    line_end: 72,
    type: 'todo',
    severity: 'critical',
    status: 'identified',
    cost_usd: 4200,
    fix_days: 3,
    votes: 14,
    created_by: 'scanner',
    created_at: new Date(Date.now() - 847 * 86400000).toISOString(),
  },
  {
    id: 'debt-2',
    repo_id: 'repo-1',
    title: 'N+1 query in user dashboard API',
    description: 'The dashboard endpoint fetches each user\'s projects in a loop inside the main user fetch. With 100 users this fires 101 database queries instead of 2.',
    file_path: 'src/api/users/dashboard.ts',
    line_start: 123,
    line_end: 145,
    type: 'performance',
    severity: 'high',
    status: 'planned',
    cost_usd: 1800,
    fix_days: 1,
    votes: 9,
    created_by: 'scanner',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
  },
  {
    id: 'debt-3',
    repo_id: 'repo-1',
    title: 'Deprecated react-query v3 — upgrade to v5 required',
    description: 'Using react-query v3 which is EOL. v5 has breaking API changes. Need to migrate all useQuery calls. Affects 23 files.',
    file_path: 'package.json',
    line_start: 1,
    line_end: 1,
    type: 'deprecated',
    severity: 'medium',
    status: 'identified',
    cost_usd: 600,
    fix_days: 4,
    votes: 5,
    created_by: 'scanner',
    created_at: new Date(Date.now() - 200 * 86400000).toISOString(),
  },
  {
    id: 'debt-4',
    repo_id: 'repo-2',
    title: 'Hardcoded API keys in environment config',
    description: 'Three API keys are hardcoded in src/config/env.ts as fallback values. These are development keys but they are committed to version control.',
    file_path: 'src/config/env.ts',
    line_start: 12,
    line_end: 18,
    type: 'security',
    severity: 'critical',
    status: 'in_progress',
    cost_usd: 8000,
    fix_days: 1,
    votes: 22,
    created_by: 'scanner',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'debt-5',
    repo_id: 'repo-2',
    title: 'PaymentModal component is 847 lines — needs splitting',
    description: 'Single file handling all payment flows, error states, retries, and UI. Cyclomatic complexity is 34. Extremely hard to test and modify safely.',
    file_path: 'src/components/PaymentModal.tsx',
    line_start: 1,
    line_end: 847,
    type: 'complexity',
    severity: 'high',
    status: 'planned',
    cost_usd: 2400,
    fix_days: 5,
    votes: 11,
    created_by: 'scanner',
    created_at: new Date(Date.now() - 180 * 86400000).toISOString(),
  },
  {
    id: 'debt-6',
    repo_id: 'repo-1',
    title: 'Dead code: unused analytics module (1,200 lines)',
    description: 'The old analytics module was replaced 6 months ago but never deleted. Still imported in 4 places but never called. Adds 48KB to bundle.',
    file_path: 'src/analytics/legacy/tracker.ts',
    line_start: 1,
    line_end: 1200,
    type: 'dead_code',
    severity: 'low',
    status: 'fixed',
    cost_usd: 200,
    fix_days: 0.5,
    votes: 3,
    fixed_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_by: 'scanner',
    created_at: new Date(Date.now() - 180 * 86400000).toISOString(),
  },
  {
    id: 'debt-7',
    repo_id: 'repo-2',
    title: 'Duplicate user validation logic in 5 endpoints',
    description: 'The same 40-line user validation block is copy-pasted across 5 different API route handlers. A bug fix must be applied 5 times.',
    file_path: 'src/api/users/',
    line_start: 1,
    line_end: 40,
    type: 'duplicate',
    severity: 'medium',
    status: 'identified',
    cost_usd: 800,
    fix_days: 2,
    votes: 7,
    created_by: 'scanner',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
]

// ── SPRINT ────────────────────────────────────────────────────────────────────
export const MOCK_SPRINT: Sprint = {
  id: 'sprint-14',
  workspace_id: 'ws-1',
  name: 'Sprint 14',
  start_date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
  end_date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
  status: 'active',
  ai_recommendation: 'Allocate 25% of this sprint to debt. Fixing debt-4 (hardcoded keys) and debt-2 (N+1 query) will recover 18% engineering velocity by Sprint 15.',
  created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
}

// ── WEEKLY STATS ──────────────────────────────────────────────────────────────
export const MOCK_WEEKLY_STATS: WeeklyStats[] = [
  { week: 'W1', added: 8, fixed: 3 },
  { week: 'W2', added: 5, fixed: 6 },
  { week: 'W3', added: 12, fixed: 4 },
  { week: 'W4', added: 3, fixed: 8 },
  { week: 'W5', added: 7, fixed: 5 },
  { week: 'W6', added: 4, fixed: 9 },
  { week: 'W7', added: 2, fixed: 7 },
]

// ── MODULE DEBT ───────────────────────────────────────────────────────────────
export const MOCK_MODULE_DEBT: ModuleDebt[] = [
  { module: 'src/auth/', items: 8, cost: 12400 },
  { module: 'src/api/users/', items: 6, cost: 8200 },
  { module: 'src/components/', items: 11, cost: 6800 },
  { module: 'src/payments/', items: 4, cost: 9100 },
  { module: 'src/analytics/', items: 3, cost: 1200 },
]

// ── ACTIVITY FEED ─────────────────────────────────────────────────────────────
export const MOCK_ACTIVITY = [
  { id: 1, type: 'fixed', user: 'Priya S.', action: 'fixed', item: 'Hardcoded API keys', time: '2m ago', color: '#00ff88' },
  { id: 2, type: 'scan', user: 'System', action: 'scan completed', item: 'api-server — 3 new items', time: '18m ago', color: '#00e5ff' },
  { id: 3, type: 'vote', user: 'Rohan K.', action: 'upvoted', item: 'Token race condition', time: '1h ago', color: '#ffd600' },
  { id: 4, type: 'added', user: 'Vikram N.', action: 'added', item: 'Missing error boundary', time: '2h ago', color: '#7c3aed' },
  { id: 5, type: 'sprint', user: 'Arjun K.', action: 'added to sprint', item: 'N+1 query fix', time: '3h ago', color: '#00e5ff' },
  { id: 6, type: 'critical', user: 'Scanner', action: 'detected critical', item: 'SQL injection risk', time: '5h ago', color: '#ff3b5c' },
]

// ── TEAM MEMBERS ──────────────────────────────────────────────────────────────
export const MOCK_TEAM: TeamMember[] = [
  {
    id: 'user-1', email: 'arjun@acme.com', name: 'Arjun Kumar',
    user_code: 'CD#4821', plan: 'team', role: 'manager',
    workspace_id: 'ws-1', onboarding_done: true,
    created_at: '', last_seen: new Date().toISOString(),
    items_fixed: 12, items_created: 3, online: true,
    current_file: 'Reviewing sprint plan',
  },
  {
    id: 'user-2', email: 'priya@acme.com', name: 'Priya Sharma',
    user_code: 'CD#2341', plan: 'team', role: 'developer',
    workspace_id: 'ws-1', onboarding_done: true,
    created_at: '', last_seen: new Date().toISOString(),
    items_fixed: 28, items_created: 8, online: true,
    current_file: 'src/auth/token.service.ts',
  },
  {
    id: 'user-3', email: 'rohan@acme.com', name: 'Rohan Verma',
    user_code: 'CD#7732', plan: 'team', role: 'developer',
    workspace_id: 'ws-1', onboarding_done: true,
    created_at: '', last_seen: new Date(Date.now() - 45 * 60000).toISOString(),
    items_fixed: 15, items_created: 12, online: false,
    current_file: 'src/api/users/dashboard.ts',
  },
  {
    id: 'user-4', email: 'aisha@acme.com', name: 'Aisha Khan',
    user_code: 'CD#5519', plan: 'team', role: 'developer',
    workspace_id: 'ws-1', onboarding_done: true,
    created_at: '', last_seen: new Date().toISOString(),
    items_fixed: 19, items_created: 5, online: true,
    current_file: 'src/components/PaymentModal.tsx',
  },
  {
    id: 'user-5', email: 'vikram@acme.com', name: 'Vikram Nair',
    user_code: 'CD#9901', plan: 'team', role: 'developer',
    workspace_id: 'ws-1', onboarding_done: false,
    created_at: '', last_seen: new Date(Date.now() - 120 * 60000).toISOString(),
    items_fixed: 7, items_created: 16, online: false,
  },
]
